"""Central Capability Registry and Catalog Generator."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, List, Optional

from jarvis.core.capabilities.models import (
    CapabilityCategory,
    CapabilityDefinition,
    CostTier,
)
from jarvis.core.capabilities.verifier_map import get_verifier_for_tool
from jarvis.tools.base import RiskLevel
from jarvis.tools.registry import ToolRegistry


# Explicit Master Capability Definitions for all 80 Registered System Tools
CAPABILITY_DEFINITIONS: List[CapabilityDefinition] = [
    # --- SYSTEM (10) ---
    CapabilityDefinition(
        id="system.time",
        category=CapabilityCategory.SYSTEM,
        description="Retrieves the current local date, time, and timezone.",
        keywords=["time", "date", "clock", "hour", "day", "current time", "what time is it"],
        examples=["What time is it?", "Tell me the current time", "What's today's date?", "Current time please"],
        counterexamples=["Set a timer for 10 minutes", "Remind me at 5pm", "How long did that take?"],
        required_slots=[],
        optional_slots=[],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="get_time",
        verifier="time_format_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="system.info",
        category=CapabilityCategory.SYSTEM,
        description="Retrieves CPU, RAM, OS version, disk usage, and host specifications.",
        keywords=["specs", "system info", "cpu", "ram", "memory usage", "hardware", "os version"],
        examples=["Show system specs", "How much RAM is free?", "What CPU do I have?", "System info"],
        counterexamples=["Check internet speed", "Is VLC installed?", "Run diagnostics"],
        required_slots=[],
        optional_slots=[],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="system_info",
        verifier="system_info_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="system.diagnostics",
        category=CapabilityCategory.SYSTEM,
        description="Runs diagnostic audit across system health, Ollama status, event loop, and processes.",
        keywords=["diagnostics", "audit", "health check", "subsystem status", "run diagnostics", "self test"],
        examples=["Run system diagnostics", "Check system health", "Audit subsystems", "Diagnostics"],
        counterexamples=["System specs", "Fix my internet", "Open task manager"],
        required_slots=[],
        optional_slots=[],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="system_diagnostics",
        verifier="diagnostic_report_probe",
        cost_tier=CostTier.LOW,
    ),
    CapabilityDefinition(
        id="system.devices",
        category=CapabilityCategory.SYSTEM,
        description="Lists connected audio input microphones, output speakers/headphones, and monitors.",
        keywords=["devices", "connected devices", "peripherals", "monitors", "screens", "audio devices"],
        examples=["Show connected devices", "What audio devices are plugged in?", "List screens and speakers"],
        counterexamples=["Is my phone connected?", "Bluetooth settings", "Volume 50"],
        required_slots=[],
        optional_slots=[],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="connected_devices",
        verifier="devices_list_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="system.microphone_status",
        category=CapabilityCategory.SYSTEM,
        description="Checks default audio input microphone availability, recording status, and sound levels.",
        keywords=["microphone", "mic status", "is mic working", "audio input health"],
        examples=["Is my microphone working?", "Check microphone status", "Mic test"],
        counterexamples=["Mute system volume", "Start dictation", "Listen to me"],
        required_slots=[],
        optional_slots=[],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="microphone_status",
        verifier="mic_active_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="system.stt_status",
        category=CapabilityCategory.SYSTEM,
        description="Checks speech-to-text (STT) Faster-Whisper model loading and latency status.",
        keywords=["stt status", "whisper status", "speech recognition health", "transcription status"],
        examples=["Check speech recognition status", "Is whisper loaded?", "STT health"],
        counterexamples=["Start dictation", "Record audio", "Check microphone"],
        required_slots=[],
        optional_slots=[],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="speech_recognition_status",
        verifier="stt_ready_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="system.wake_word_status",
        category=CapabilityCategory.SYSTEM,
        description="Checks status and sensitivity of the openWakeWord local engine.",
        keywords=["wake word", "openwakeword status", "wake word engine", "is wake word active"],
        examples=["Check wake word status", "Is wake word detection enabled?", "Wake word health"],
        counterexamples=["Change wake word", "Mute mic", "Hey Jarvis"],
        required_slots=[],
        optional_slots=[],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="wake_word_status",
        verifier="wake_word_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="system.voice_set",
        category=CapabilityCategory.SYSTEM,
        description="Changes the active Piper TTS synthesis voice between male and female models.",
        keywords=["change voice", "switch voice", "male voice", "female voice", "set voice"],
        examples=["Switch to female voice", "Change voice to male", "Set voice female", "Use male voice"],
        counterexamples=["Speak louder", "Mute volume", "Stop talking"],
        required_slots=["gender"],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="set_voice",
        verifier="tts_voice_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="system.dashboard",
        category=CapabilityCategory.SYSTEM,
        description="Displays the interactive JARVIS desktop UI monitoring dashboard.",
        keywords=["dashboard", "show dashboard", "open dashboard", "open ui", "status screen"],
        examples=["Open dashboard", "Show dashboard", "Display status dashboard"],
        counterexamples=["Show desktop", "Open settings", "Run diagnostics"],
        required_slots=[],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="show_dashboard",
        verifier="window_visible_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="system.wake_greeting",
        category=CapabilityCategory.SYSTEM,
        description="Generates a contextual natural audio greeting upon user wake or presence.",
        keywords=["wake greeting", "hello jarvis", "morning greeting", "greet me"],
        examples=["Good morning Jarvis", "Wake up Jarvis", "Greet me"],
        counterexamples=["What time is it?", "Tell me a joke", "Morning briefing"],
        required_slots=[],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="wake_greeting",
        verifier="greeting_spoken_probe",
        cost_tier=CostTier.FREE,
    ),

    # --- APP (7) ---
    CapabilityDefinition(
        id="app.open",
        category=CapabilityCategory.APP,
        description="Resolves and launches an application, local software, or registered web app by name.",
        keywords=["open", "launch", "start", "run", "open app", "launch program", "start software"],
        examples=["Open Chrome", "Launch VS Code", "Start Calculator", "Open Notepad", "Run Spotify"],
        counterexamples=["Close Chrome", "Is Chrome installed?", "Open index.html", "Install Chrome"],
        required_slots=["name"],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="open_app",
        verifier="process_running_probe",
        recovery_methods=["NATIVE", "POWERSHELL", "UIA"],
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="app.close",
        category=CapabilityCategory.APP,
        description="Terminates or gracefully closes a running application by process name or title.",
        keywords=["close app", "quit app", "exit application", "kill process", "shut down app"],
        examples=["Close Chrome", "Quit Notepad", "Close Spotify", "Exit VS Code"],
        counterexamples=["Close window", "Minimize Chrome", "Uninstall Chrome", "Open Chrome"],
        required_slots=["name"],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="close_app",
        verifier="process_terminated_probe",
        recovery_methods=["NATIVE", "POWERSHELL"],
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="app.check_installed",
        category=CapabilityCategory.APP,
        description="Queries the AppCatalog to verify whether a specific application is installed on this PC.",
        keywords=["is installed", "check installed", "do i have", "has application"],
        examples=["Is VLC installed?", "Do I have Chrome?", "Check if Spotify is installed", "Is VS Code on this PC?"],
        counterexamples=["Where is VLC installed?", "Install VLC", "Open VLC", "Uninstall VLC"],
        required_slots=["name"],
        optional_slots=[],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="check_app_installed",
        verifier="catalog_query_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="app.get_location",
        category=CapabilityCategory.APP,
        description="Retrieves the verified executable path and installation folder of an installed software.",
        keywords=["where is installed", "executable path", "install directory", "app path"],
        examples=["Where is VLC installed?", "Find executable for Chrome", "Where is VS Code located?"],
        counterexamples=["Is VLC installed?", "Open VLC", "Where are my downloads?"],
        required_slots=["name"],
        optional_slots=[],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="get_app_location",
        verifier="path_exists_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="app.list_installed",
        category=CapabilityCategory.APP,
        description="Lists all verified installed applications and Start Menu software tracked in the AppCatalog.",
        keywords=["list installed apps", "show applications", "all software", "installed programs", "app catalog", "programs registered", "registered programs", "all programs"],
        examples=["Show installed applications", "List all my software", "What apps are installed?", "Show all programs registered in the app catalog"],
        counterexamples=["List files in directory", "Refresh applications", "What devices are connected?"],
        required_slots=[],
        optional_slots=["limit"],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="list_installed_applications",
        verifier="catalog_list_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="app.refresh_catalog",
        category=CapabilityCategory.APP,
        description="Triggers a fresh scan across Windows registry, Start Menu, UWP, and PATH without modifying system PATH.",
        keywords=["refresh applications", "rescan apps", "update app catalog", "reload installed software"],
        examples=["Refresh applications", "Rescan installed programs", "Update application catalog"],
        counterexamples=["Show installed applications", "Refresh browser page", "Clean desktop"],
        required_slots=[],
        optional_slots=[],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="refresh_applications",
        verifier="catalog_refresh_probe",
        cost_tier=CostTier.LOW,
    ),
    CapabilityDefinition(
        id="app.install_software",
        category=CapabilityCategory.APP,
        description="Installs a verified software package via trusted package manager (winget), verifies install, and updates AppCatalog.",
        keywords=["install", "download and install", "get software", "setup app", "winget install"],
        examples=["Install VLC", "Install VS Code", "Install Google Chrome", "Download and install 7-Zip"],
        counterexamples=["Is VLC installed?", "Open VLC", "Uninstall VLC", "Update Windows"],
        required_slots=["package_name"],
        optional_slots=["source"],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="install_software",
        verifier="app_catalog_resolved_probe",
        recovery_methods=["POWERSHELL"],
        cost_tier=CostTier.EXPENSIVE,
    ),

    # --- WINDOWS (14) ---
    CapabilityDefinition(
        id="windows.close_window",
        category=CapabilityCategory.WINDOWS,
        description="Closes the currently active foreground window via Win32 API in under 200 microseconds.",
        keywords=["close window", "close this window", "close active window", "dismiss window"],
        examples=["Close window", "Close this window", "Close the current window"],
        counterexamples=["Close Chrome", "Minimize window", "Show desktop"],
        required_slots=[],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="close_window",
        verifier="active_window_changed_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="windows.minimize_window",
        category=CapabilityCategory.WINDOWS,
        description="Minimizes the currently active foreground window to the taskbar.",
        keywords=["minimize", "minimize window", "minimize this", "hide window"],
        examples=["Minimize window", "Minimize this window", "Minimize active window"],
        counterexamples=["Maximize window", "Show desktop", "Close window"],
        required_slots=[],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="minimize_window",
        verifier="window_state_minimized_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="windows.maximize_window",
        category=CapabilityCategory.WINDOWS,
        description="Maximizes the currently active foreground window to fill the monitor display.",
        keywords=["maximize", "maximize window", "full window", "expand window", "fullscreen", "full screen", "fulll screen", "fill screen"],
        examples=["Maximize window", "Maximize this", "Full screen this window", "Full screen", "Fullscreen", "Make it full screen"],
        counterexamples=["Minimize window", "Close window", "Snap left", "Take screenshot"],
        required_slots=[],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="maximize_window",
        verifier="window_state_maximized_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="windows.show_desktop",
        category=CapabilityCategory.WINDOWS,
        description="Minimizes all open windows and toggles display to the Windows desktop (Win+D).",
        keywords=["show desktop", "minimize all", "go to desktop", "toggle desktop"],
        examples=["Show desktop", "Minimize all windows", "Go to desktop"],
        counterexamples=["Show dashboard", "Open desktop folder", "Close all windows"],
        required_slots=[],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="show_desktop",
        verifier="desktop_foreground_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="windows.volume_get",
        category=CapabilityCategory.WINDOWS,
        description="Retrieves the current master audio output volume percentage and mute status.",
        keywords=["volume", "what volume", "current volume", "audio level", "sound level"],
        examples=["What's the volume?", "Check volume level", "Tell me the volume"],
        counterexamples=["Set volume to 50", "Mute volume", "Volume up"],
        required_slots=[],
        optional_slots=[],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="volume_get",
        verifier="volume_read_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="windows.volume_set",
        category=CapabilityCategory.WINDOWS,
        description="Sets the master audio output volume to a specific percentage (0 to 100).",
        keywords=["set volume", "volume", "sound to", "turn volume to"],
        examples=["Volume 50", "Set volume to 30", "Volume 80 percent", "Turn sound down to 20"],
        counterexamples=["What is the volume?", "Mute audio", "Volume up", "Turn the brightness down", "Set brightness to 50", "Brightness 30%"],
        required_slots=["percent"],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="volume_set",
        verifier="pycaw_volume_match_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="windows.brightness_set",
        category=CapabilityCategory.WINDOWS,
        description="Sets the display screen brightness to a specific percentage (0 to 100).",
        keywords=["brightness", "screen brightness", "display brightness", "dim screen", "turn brightness", "set brightness"],
        examples=["Turn the brightness down to 30 percent", "Set brightness to 50", "Make screen brighter", "Dim the brightness to 20%"],
        counterexamples=["Volume 50", "Turn sound down", "Take screenshot"],
        required_slots=["percent"],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="brightness_set",
        verifier="brightness_match_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="windows.brightness_get",
        category=CapabilityCategory.WINDOWS,
        description="Gets the current display screen brightness percentage.",
        keywords=["brightness", "what is brightness", "check brightness", "current brightness"],
        examples=["What is the screen brightness?", "Check brightness level", "Current brightness"],
        counterexamples=["Set brightness to 50", "Volume"],
        required_slots=[],
        optional_slots=[],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="brightness_get",
        verifier="brightness_read_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="windows.top_memory_processes",
        category=CapabilityCategory.WINDOWS,
        description="Lists the running applications and programs consuming the most RAM/memory.",
        keywords=["memory", "ram", "top memory", "most memory", "programs using memory", "apps using ram", "highest memory"],
        examples=["Which programs are using the most memory?", "What apps are using the most RAM?", "Show memory hogs", "Top memory processes"],
        counterexamples=["System specs", "Close chrome", "Show all files"],
        required_slots=[],
        optional_slots=[],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="top_memory_processes",
        verifier="process_list_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="windows.volume_mute",
        category=CapabilityCategory.WINDOWS,
        description="Mutes system audio output for total silence.",
        keywords=["mute", "mute audio", "mute sound", "total silence", "silence audio", "silence", "be quiet", "shut up audio"],
        examples=["Mute volume", "Total silence please", "Mute sound"],
        counterexamples=["Unmute", "Volume 50", "Play music"],
        required_slots=[],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="volume_set",
        verifier="volume_read_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="windows.volume_unmute",
        category=CapabilityCategory.WINDOWS,
        description="Unmutes system audio output restoring previous volume level.",
        keywords=["unmute", "unmute audio", "unmute sound", "sound back on", "turn sound back on", "sound on", "audio back"],
        examples=["Unmute volume", "Sound back on", "Turn sound back on"],
        counterexamples=["Mute volume", "Silence", "Stop audio"],
        required_slots=[],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="volume_set",
        verifier="volume_read_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="windows.screenshot",
        category=CapabilityCategory.WINDOWS,
        description="Captures a full screenshot of the primary monitor and saves it to a verified PNG file.",
        keywords=["screenshot", "take screenshot", "capture screen", "snapshot monitor", "screen grab"],
        examples=["Take a screenshot", "Capture my screen", "Take snapshot", "Screen capture"],
        counterexamples=["Take a photo with phone", "Record video", "Desktop UI snapshot", "Make it full screen", "Maximize window"],
        required_slots=[],
        optional_slots=["path"],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="take_screenshot",
        verifier="png_file_valid_probe",
        cost_tier=CostTier.LOW,
    ),
    CapabilityDefinition(
        id="windows.media_control",
        category=CapabilityCategory.WINDOWS,
        description="Dispatches multimedia hardware keys: play, pause, next track, previous track, or mute.",
        keywords=["media", "play music", "pause music", "next song", "previous track", "stop playback"],
        examples=["Pause playback", "Resume music", "Next track", "Previous song", "Mute audio"],
        counterexamples=["Play lo-fi on YouTube", "Volume 50", "Open Spotify"],
        required_slots=["action"],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="media_control",
        verifier="media_key_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="windows.desktop_ui_click",
        category=CapabilityCategory.WINDOWS,
        description="Clicks an interactive button, menu item, or tab inside an active desktop window via UI Automation.",
        keywords=["click button", "click menu", "press button in app", "ui click"],
        examples=["Click Save button", "Click File menu", "Click Submit in application"],
        counterexamples=["Click link on website", "Right click file", "Close window"],
        required_slots=["target"],
        optional_slots=["app_title"],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="desktop_ui_click",
        verifier="uia_action_probe",
        recovery_methods=["UIA", "VISION"],
        cost_tier=CostTier.LOW,
    ),
    CapabilityDefinition(
        id="windows.desktop_ui_snapshot",
        category=CapabilityCategory.WINDOWS,
        description="Captures accessibility hierarchy and interactive elements of the active desktop window via UI Automation.",
        keywords=["window elements", "read screen ui", "inspect window", "desktop accessibility tree"],
        examples=["Inspect active window controls", "What buttons are on screen?", "Snapshot desktop UI"],
        counterexamples=["Take screenshot", "Browser snapshot", "List directory"],
        required_slots=[],
        optional_slots=["app_title"],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="desktop_ui_snapshot",
        verifier="uia_tree_probe",
        recovery_methods=["UIA", "VISION"],
        cost_tier=CostTier.LOW,
    ),
    CapabilityDefinition(
        id="windows.snap",
        category=CapabilityCategory.WINDOWS,
        description="Snaps the active window to screen boundaries (left, right, top, bottom, or corners).",
        keywords=["snap window", "snap left", "snap right", "dock window", "half screen"],
        examples=["Snap window left", "Snap window right", "Snap this to the left"],
        counterexamples=["Close window", "Minimize window"],
        required_slots=["direction"],
        optional_slots=["window_title"],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="snap_window",
        verifier="window_state_minimized_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="windows.arrange",
        category=CapabilityCategory.WINDOWS,
        description="Arranges two applications side-by-side or lays out multiple open windows in a grid.",
        keywords=["arrange windows", "side by side", "arrange two applications", "tile windows", "split screen"],
        examples=["Arrange windows side by side", "Arrange Chrome and VS Code side by side", "Tile windows"],
        counterexamples=["Close all windows", "Show desktop"],
        required_slots=[],
        optional_slots=["layout", "app1", "app2"],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="arrange_windows",
        verifier="window_state_minimized_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="windows.move_resize",
        category=CapabilityCategory.WINDOWS,
        description="Moves, resizes, or restores the currently active window.",
        keywords=["move window", "resize window", "restore window", "window size"],
        examples=["Restore window", "Resize window to 800 by 600", "Move window"],
        counterexamples=["Minimize window", "Maximize window"],
        required_slots=["action"],
        optional_slots=["x", "y", "width", "height"],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="move_resize_window",
        verifier="window_state_minimized_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="windows.switch",
        category=CapabilityCategory.WINDOWS,
        description="Switches to the previous application (Alt+Tab) or brings a named window to the foreground.",
        keywords=["switch window", "switch to previous window", "switch to", "next window", "alt tab"],
        examples=["Switch to previous window", "Switch window", "Switch to Chrome"],
        counterexamples=["Close window", "Open app"],
        required_slots=[],
        optional_slots=["target"],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="switch_window",
        verifier="active_window_changed_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="windows.settings",
        category=CapabilityCategory.WINDOWS,
        description="Opens Windows Settings pages: sound, display, network, Wi-Fi, apps, Task Manager, system info.",
        keywords=["windows settings", "sound settings", "display settings", "network settings", "wifi settings", "open settings", "task manager"],
        examples=["Open sound settings", "Open display settings", "Open network settings", "Open Task Manager", "Open Windows Settings"],
        counterexamples=["System specs", "Check brightness"],
        required_slots=["page"],
        optional_slots=[],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="open_system_settings",
        verifier="default_exit_code_verifier",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="windows.known_folder",
        category=CapabilityCategory.WINDOWS,
        description="Opens Windows Known Folders (Downloads, Documents, Desktop, Pictures, Music, Videos) resolving exact paths dynamically.",
        keywords=["open downloads", "open documents", "open desktop folder", "open pictures", "open file explorer", "my downloads", "my documents"],
        examples=["Open Downloads folder", "Open Documents", "Open Desktop folder", "Open Pictures", "Open File Explorer"],
        counterexamples=["List files in downloads", "Clean downloads"],
        required_slots=["folder"],
        optional_slots=[],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="open_known_folder",
        verifier="path_exists_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="windows.power",
        category=CapabilityCategory.WINDOWS,
        description="Controls system power state: Lock PC, Sleep PC, or confirmed Restart/Shutdown.",
        keywords=["lock pc", "lock computer", "sleep pc", "restart pc", "shut down pc", "turn off pc"],
        examples=["Lock the PC", "Sleep PC", "Restart PC", "Shut down the computer"],
        counterexamples=["Close window", "Close app"],
        required_slots=["action"],
        optional_slots=["confirmation_ticket"],
        risk_level=RiskLevel.DESTRUCTIVE,
        target_tool="system_power_control",
        verifier="default_exit_code_verifier",
        cost_tier=CostTier.LOW,
    ),
    CapabilityDefinition(
        id="windows.dialog",
        category=CapabilityCategory.WINDOWS,
        description="Inspects active window for modal/confirmation dialogs, checks if app is not responding, or responds to dialogs.",
        keywords=["dialog", "modal dialog", "check if app is responding", "confirm dialog", "dismiss dialog"],
        examples=["Check if app is responding", "Confirm dialog", "Dismiss dialog", "Detect dialog"],
        counterexamples=["Close window", "Desktop UI click"],
        required_slots=["action"],
        optional_slots=["window_title"],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="dialog_interaction",
        verifier="default_exit_code_verifier",
        cost_tier=CostTier.FREE,
    ),

    # --- BROWSER (6) ---
    CapabilityDefinition(
        id="browser.open_url",
        category=CapabilityCategory.BROWSER,
        description="Opens a web URL in the managed Playwright browser session.",
        keywords=["open website", "browse to", "open url", "go to web page"],
        examples=["Open example.com", "Go to https://github.com", "Open reddit.com in browser"],
        counterexamples=["Open Chrome", "Search the web for python", "Play youtube"],
        required_slots=["url"],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="browser_open_url",
        verifier="browser_url_match_probe",
        cost_tier=CostTier.MEDIUM,
    ),
    CapabilityDefinition(
        id="browser.navigate",
        category=CapabilityCategory.BROWSER,
        description="Navigates the currently active browser tab to a new URL.",
        keywords=["navigate to", "browser navigate", "go to link"],
        examples=["Navigate to https://wikipedia.org", "Go to docs.python.org in active tab"],
        counterexamples=["Open Chrome", "Browser back", "Click link"],
        required_slots=["url"],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="browser_navigate",
        verifier="browser_url_match_probe",
        cost_tier=CostTier.MEDIUM,
    ),
    CapabilityDefinition(
        id="browser.click",
        category=CapabilityCategory.BROWSER,
        description="Clicks an interactive DOM element, link, or button on the active web page.",
        keywords=["click link", "click web button", "browser click", "select web element"],
        examples=["Click the login button", "Click the first search result", "Click Download link"],
        counterexamples=["Desktop UI click", "Click Save in Notepad", "Browser navigate"],
        required_slots=["selector"],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="browser_click",
        verifier="browser_dom_mutation_probe",
        recovery_methods=["NATIVE", "VISION"],
        cost_tier=CostTier.MEDIUM,
    ),
    CapabilityDefinition(
        id="browser.type",
        category=CapabilityCategory.BROWSER,
        description="Enters text into an input field or search box on the active web page.",
        keywords=["type into browser", "fill web form", "enter text online", "browser search input"],
        examples=["Type 'artificial intelligence' in search box", "Fill email input with test@example.com"],
        counterexamples=["Dictate text into Notepad", "Send WhatsApp message", "Create note"],
        required_slots=["selector", "text"],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="browser_type",
        verifier="browser_dom_value_probe",
        recovery_methods=["NATIVE", "VISION"],
        cost_tier=CostTier.MEDIUM,
    ),
    CapabilityDefinition(
        id="browser.snapshot",
        category=CapabilityCategory.BROWSER,
        description="Extracts the accessibility tree and interactive elements of the active browser page.",
        keywords=["browser snapshot", "read web page", "inspect web elements", "get page text"],
        examples=["Snapshot active web page", "What links are on this page?", "Read browser content"],
        counterexamples=["Take screenshot", "Desktop UI snapshot", "Search web"],
        required_slots=[],
        optional_slots=[],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="browser_snapshot",
        verifier="browser_tree_probe",
        cost_tier=CostTier.LOW,
    ),
    CapabilityDefinition(
        id="browser.play_youtube",
        category=CapabilityCategory.BROWSER,
        description="Opens YouTube and searches for or plays a specified video, artist, or song query.",
        keywords=["youtube", "play video", "watch on youtube", "play song on youtube"],
        examples=["Play lo-fi music on YouTube", "Open YouTube and search for quantum computing", "Watch Python tutorial on YouTube"],
        counterexamples=["Play local mp3", "Resume music", "Open Spotify"],
        required_slots=["query"],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="play_youtube",
        verifier="browser_url_match_probe",
        cost_tier=CostTier.MEDIUM,
    ),

    # --- FILE (12) ---
    CapabilityDefinition(
        id="file.list_directory",
        category=CapabilityCategory.FILE,
        description="Lists the files and subdirectories inside a specific local directory path.",
        keywords=["list files", "dir", "ls", "what is inside folder", "contents of directory", "list folder", "show folder", "show directory", "contents of my desktop", "the contents of", "what files are in", "see what files", "show files in", "files in documents", "files in downloads", "pictures folder", "music folder", "videos folder"],
        examples=["List files in Downloads", "What's inside C:/Projects?", "List directory C:/Users/Documents"],
        counterexamples=["Find file budget.xlsx", "Open folder", "Create folder"],
        required_slots=["path"],
        optional_slots=["limit"],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="list_directory",
        verifier="directory_read_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="file.find",
        category=CapabilityCategory.FILE,
        description="Searches indexed local files using cascaded FTS5 full-text search and semantic scoring.",
        keywords=["find file", "search files", "where is file", "locate document"],
        examples=["Find my project report PDF", "Search for budget.xlsx", "Where is resume.docx?"],
        counterexamples=["Search the web for python", "Search notes", "Find text in document"],
        required_slots=["query"],
        optional_slots=["extension", "limit"],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="find_file",
        verifier="search_results_probe",
        cost_tier=CostTier.LOW,
    ),
    CapabilityDefinition(
        id="file.open",
        category=CapabilityCategory.FILE,
        description="Opens an existing local file using its registered Windows default application.",
        keywords=["open file", "view document", "open pdf", "launch file"],
        examples=["Open my resume.pdf", "Open C:/Projects/data.csv", "Open the report we just found"],
        counterexamples=["Open Chrome", "Find file", "Read file metadata"],
        required_slots=["path"],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="open_file",
        verifier="file_open_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="file.create_folder",
        category=CapabilityCategory.FILE,
        description="Creates a new directory or folder at the specified path if it does not already exist.",
        keywords=["create folder", "make directory", "new folder", "mkdir"],
        examples=["Create a folder named Projects on Desktop", "Make new folder C:/Data/Backup", "Create directory test"],
        counterexamples=["Delete folder", "Move folder", "List directory"],
        required_slots=["path"],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="create_folder",
        verifier="path_is_dir_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="file.rename",
        category=CapabilityCategory.FILE,
        description="Renames an existing file or directory with conflict checking and collision prevention.",
        keywords=["rename file", "change file name", "rename folder"],
        examples=["Rename old.txt to new.txt", "Rename document draft to final_report.pdf"],
        counterexamples=["Move file", "Copy file", "Batch rename"],
        required_slots=["path", "new_name"],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="rename_file",
        verifier="new_name_exists_old_absent_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="file.move",
        category=CapabilityCategory.FILE,
        description="Relocates a file or directory from source to destination path with TOCTOU checks.",
        keywords=["move file", "relocate file", "move folder to"],
        examples=["Move report.pdf to Desktop", "Move downloaded file to C:/Archives"],
        counterexamples=["Copy file", "Rename file", "Delete file"],
        required_slots=["source", "destination"],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="move_file",
        verifier="dest_exists_source_absent_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="file.copy",
        category=CapabilityCategory.FILE,
        description="Creates a duplicate copy of a file at the specified destination path.",
        keywords=["copy file", "duplicate file", "backup file to"],
        examples=["Copy notes.txt to C:/Backup", "Duplicate budget.xlsx as budget_copy.xlsx"],
        counterexamples=["Move file", "Send file to phone", "Find duplicates"],
        required_slots=["source", "destination"],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="copy_file",
        verifier="destination_file_exists_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="file.delete",
        category=CapabilityCategory.FILE,
        description="Safely moves a local file or folder to the Windows Recycle Bin using send2trash.",
        keywords=["delete file", "remove file", "send to recycle bin", "trash document"],
        examples=["Delete test.tmp from Desktop", "Remove outdated_draft.docx", "Trash temporary folder"],
        counterexamples=["Don't delete that", "Move file", "Clear cache"],
        required_slots=["path"],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="delete_file",
        verifier="source_absent_in_recycle_bin_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="file.read_metadata",
        category=CapabilityCategory.FILE,
        description="Reads size in bytes, modification timestamp, and MIME type of a local file path.",
        keywords=["file metadata", "file size", "when was file modified", "file info"],
        examples=["Check size of video.mp4", "When was report.pdf last modified?", "Get metadata for data.csv"],
        counterexamples=["Read file content", "Document QA", "Find duplicates"],
        required_slots=["path"],
        optional_slots=[],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="read_file_metadata",
        verifier="metadata_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="file.batch_rename",
        category=CapabilityCategory.FILE,
        description="Applies systematic pattern or regex renaming across multiple files in a directory with dry-run preview.",
        keywords=["batch rename", "rename all files", "prefix all files", "systematic rename"],
        examples=["Batch rename all images in Photos to vacation_001.jpg", "Add prefix 2026_ to all files in Documents"],
        counterexamples=["Rename single file", "Organize downloads"],
        required_slots=["directory", "pattern"],
        optional_slots=["dry_run"],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="batch_rename",
        verifier="batch_rename_probe",
        cost_tier=CostTier.LOW,
    ),
    CapabilityDefinition(
        id="file.organize_downloads",
        category=CapabilityCategory.FILE,
        description="Automatically sorts loose files in the Downloads folder into subdirectories by file type.",
        keywords=["organize downloads", "clean downloads", "sort downloads folder", "tidy up downloads", "downloads mess", "downloads are a mess", "downloads is a mess", "clean up downloads"],
        examples=["Organize my Downloads folder", "Clean up Downloads by sorting documents and images"],
        counterexamples=["List files in downloads", "Delete downloads"],
        required_slots=[],
        optional_slots=["downloads_path"],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="organize_downloads",
        verifier="downloads_organized_probe",
        cost_tier=CostTier.LOW,
    ),
    CapabilityDefinition(
        id="file.find_duplicates",
        category=CapabilityCategory.FILE,
        description="Identifies identical duplicate files across a directory tree based on exact size and SHA-256 content hashes.",
        keywords=["find duplicates", "check duplicate files", "duplicate finder", "redundant files"],
        examples=["Find duplicate files in Documents", "Scan C:/Media for duplicate images"],
        counterexamples=["Copy file", "Find file", "Find notes"],
        required_slots=["directory"],
        optional_slots=[],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="find_duplicates",
        verifier="duplicates_probe",
        cost_tier=CostTier.LOW,
    ),

    # --- RAG & KNOWLEDGE (12) ---
    CapabilityDefinition(
        id="rag.document_qa",
        category=CapabilityCategory.RAG,
        description="Answers questions based on local document contents with verifiable section citations.",
        keywords=["document qa", "ask document", "what does the pdf say", "summarize file"],
        examples=["What are the revenue figures in the financial report?", "Summarize Section 3 of project_plan.pdf"],
        counterexamples=["Search the web", "Find file", "Read file metadata"],
        required_slots=["query"],
        optional_slots=["file_path"],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="document_qa",
        verifier="qa_citation_probe",
        cost_tier=CostTier.MEDIUM,
    ),
    CapabilityDefinition(
        id="rag.search_web",
        category=CapabilityCategory.RAG,
        description="Performs a real-time web search for recent news, technical documentation, or factual queries.",
        keywords=["search web", "google search", "search internet", "look up online"],
        examples=["Search the web for artificial intelligence news", "Look up latest Python 3.12 release notes online"],
        counterexamples=["Find file", "Search local notes", "Browse to url"],
        required_slots=["query"],
        optional_slots=["limit"],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="search_web",
        verifier="web_results_probe",
        cost_tier=CostTier.MEDIUM,
    ),
    CapabilityDefinition(
        id="rag.search_news",
        category=CapabilityCategory.RAG,
        description="Searches for verified real-time Indian and global news headlines.",
        keywords=["search news", "india news", "current headlines", "live news"],
        examples=["Search for latest news in India", "What are today's top tech headlines?"],
        counterexamples=["Search notes", "RSS latest", "Search web for python"],
        required_slots=[],
        optional_slots=["topic"],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="search_news",
        verifier="news_results_probe",
        cost_tier=CostTier.MEDIUM,
    ),
    CapabilityDefinition(
        id="rag.rss_latest",
        category=CapabilityCategory.RAG,
        description="Fetches recent unread articles and news headlines from configured RSS/Atom feeds.",
        keywords=["rss feeds", "feed headlines", "latest rss", "freshrss"],
        examples=["Fetch latest RSS headlines", "What's new on my RSS feeds?"],
        counterexamples=["Search web", "Morning briefing"],
        required_slots=[],
        optional_slots=["limit"],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="rss_latest",
        verifier="rss_probe",
        cost_tier=CostTier.LOW,
    ),
    CapabilityDefinition(
        id="rag.capture_note",
        category=CapabilityCategory.RAG,
        description="Quickly saves a short thought, snippet, or reminder into the local markdown notes system.",
        keywords=["take note", "save note", "note down", "write down snippet", "jot down"],
        examples=["Note down that meeting is at 4 PM", "Capture note: buy groceries tomorrow", "Write down api key idea"],
        counterexamples=["Search notes", "Memos create", "Dictate text"],
        required_slots=["text"],
        optional_slots=["title"],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="capture_note",
        verifier="note_file_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="rag.search_notes",
        category=CapabilityCategory.RAG,
        description="Searches previously captured local markdown notes using full-text keywords.",
        keywords=["search notes", "find note", "look up my notes", "what did I note about"],
        examples=["Search notes for grocery list", "Find my notes about project architecture", "Look up note meeting"],
        counterexamples=["Search the web", "Find file", "Document QA"],
        required_slots=["query"],
        optional_slots=[],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="search_notes",
        verifier="notes_results_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="rag.memos_create",
        category=CapabilityCategory.RAG,
        description="Posts a note or reminder into the local Memos inbox instance.",
        keywords=["memos create", "post to memos", "save memo", "add to memos"],
        examples=["Add a memo about server restart", "Save to Memos: test deployment"],
        counterexamples=["Capture note", "Memos recent", "Send whatsapp"],
        required_slots=["content"],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="memos_create",
        verifier="memos_api_probe",
        cost_tier=CostTier.LOW,
    ),
    CapabilityDefinition(
        id="rag.memos_recent",
        category=CapabilityCategory.RAG,
        description="Retrieves the most recent human-readable memos and reminders from Memos inbox.",
        keywords=["memos recent", "recent memos", "check memos", "list memos"],
        examples=["Show recent memos", "What's in my Memos inbox?", "List my latest memos"],
        counterexamples=["Memos create", "Search notes", "Morning briefing"],
        required_slots=[],
        optional_slots=["limit"],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="memos_recent",
        verifier="memos_list_probe",
        cost_tier=CostTier.LOW,
    ),
    CapabilityDefinition(
        id="rag.morning_briefing",
        category=CapabilityCategory.RAG,
        description="Compiles and speaks an integrated morning briefing covering system health, RSS, weather, and tasks.",
        keywords=["morning briefing", "daily briefing", "brief me", "start my day"],
        examples=["Give me my morning briefing", "What's my briefing for today?", "Good morning, brief me"],
        counterexamples=["Personal briefing", "System diagnostics", "RSS latest"],
        required_slots=[],
        optional_slots=[],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="morning_briefing",
        verifier="briefing_compiled_probe",
        cost_tier=CostTier.LOW,
    ),
    CapabilityDefinition(
        id="rag.personal_briefing",
        category=CapabilityCategory.RAG,
        description="Generates an actionable daily briefing focused on active projects, tasks, and recent notes.",
        keywords=["personal briefing", "my tasks today", "work briefing", "project summary"],
        examples=["What are my priorities today?", "Give me my personal briefing", "Summarize active tasks"],
        counterexamples=["Morning briefing", "System info"],
        required_slots=[],
        optional_slots=[],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="personal_briefing",
        verifier="briefing_compiled_probe",
        cost_tier=CostTier.LOW,
    ),
    CapabilityDefinition(
        id="rag.meeting_notes",
        category=CapabilityCategory.RAG,
        description="Extracts structured summary, key decisions, and action items from a meeting transcript.",
        keywords=["meeting notes", "summarize meeting", "extract action items", "meeting transcript"],
        examples=["Generate meeting notes from transcript.txt", "Extract action items from the meeting log"],
        counterexamples=["Document QA", "Dictate text", "Capture note"],
        required_slots=["transcript"],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="generate_meeting_notes",
        verifier="action_items_probe",
        cost_tier=CostTier.MEDIUM,
    ),
    CapabilityDefinition(
        id="rag.ollama_chat",
        category=CapabilityCategory.RAG,
        description="Queries the local Ollama LLM for general knowledge, coding assistance, or reasoning.",
        keywords=["ask jarvis", "explain concept", "coding help", "general knowledge", "tell me about"],
        examples=["Explain how quantum entanglement works", "Why is the sky blue?", "Write a quick Python sort function"],
        counterexamples=["Run powershell command", "Open app", "Search web"],
        required_slots=["prompt"],
        optional_slots=[],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="ollama_chat",
        verifier="llm_response_probe",
        cost_tier=CostTier.MEDIUM,
    ),

    # --- PHONE (9) ---
    CapabilityDefinition(
        id="phone.status",
        category=CapabilityCategory.PHONE,
        description="Queries connected Android device status, battery percentage, and scrcpy readiness via ADB.",
        keywords=["phone status", "is phone connected", "android status", "phone battery"],
        examples=["Is my phone connected?", "Check phone status", "What is my phone's battery level?"],
        counterexamples=["Mirror phone screen", "Send file to phone", "Send notification"],
        required_slots=[],
        optional_slots=[],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="android_status",
        verifier="adb_device_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="phone.mirror_open",
        category=CapabilityCategory.PHONE,
        description="Spawns low-latency desktop phone screen mirroring via scrcpy over USB or Wi-Fi.",
        keywords=["mirror phone", "show phone screen", "open phone control", "scrcpy"],
        examples=["Show my phone screen on PC", "Mirror phone", "Open phone control"],
        counterexamples=["Close phone mirror", "Phone status", "Send text to phone"],
        required_slots=[],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="android_open_control",
        verifier="scrcpy_process_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="phone.mirror_close",
        category=CapabilityCategory.PHONE,
        description="Closes the active scrcpy screen mirroring window.",
        keywords=["close phone mirror", "stop mirroring", "close phone control"],
        examples=["Close phone control", "Stop mirroring phone screen", "Close scrcpy"],
        counterexamples=["Open phone control", "Close app Chrome", "Close window"],
        required_slots=[],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="android_close_control",
        verifier="scrcpy_closed_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="phone.home",
        category=CapabilityCategory.PHONE,
        description="Presses the Home navigation button on the connected Android phone via ADB.",
        keywords=["phone home", "go to phone home screen", "android home"],
        examples=["Press home on my phone", "Go to phone home screen"],
        counterexamples=["Show desktop", "Phone back", "Mirror phone"],
        required_slots=[],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="android_home",
        verifier="adb_keyevent_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="phone.back",
        category=CapabilityCategory.PHONE,
        description="Presses the Back navigation button on the connected Android phone via ADB.",
        keywords=["phone back", "android back button", "press back on phone"],
        examples=["Press back on my phone", "Go back on Android"],
        counterexamples=["Phone home", "Browser back", "Close app"],
        required_slots=[],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="android_back",
        verifier="adb_keyevent_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="phone.open_app",
        category=CapabilityCategory.PHONE,
        description="Launches an Android application or package on the connected phone via ADB intent.",
        keywords=["open app on phone", "launch phone app", "open android app"],
        examples=["Open WhatsApp on my phone", "Launch Camera on Android", "Open Spotify on phone"],
        counterexamples=["Open Spotify on PC", "Mirror phone", "Phone status"],
        required_slots=["app_name"],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="android_open_app",
        verifier="adb_focused_window_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="phone.send_file",
        category=CapabilityCategory.PHONE,
        description="Transfers a local file from PC to connected phone over local Wi-Fi via LocalSend protocol.",
        keywords=["send file to phone", "transfer file to phone", "localsend file"],
        examples=["Send report.pdf to my phone", "Transfer image.png to phone via LocalSend"],
        counterexamples=["Send text to phone", "Copy file", "Send notification"],
        required_slots=["path"],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="localsend_file",
        verifier="localsend_probe",
        cost_tier=CostTier.LOW,
    ),
    CapabilityDefinition(
        id="phone.send_text",
        category=CapabilityCategory.PHONE,
        description="Transfers clipboard text or URL to phone via LocalSend protocol.",
        keywords=["send text to phone", "send clipboard to phone", "localsend text"],
        examples=["Send clipboard text to my phone", "Push link https://github.com to phone"],
        counterexamples=["Send file to phone", "Send WhatsApp message", "Notification send"],
        required_slots=["text"],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="localsend_text",
        verifier="localsend_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="phone.send_notification",
        category=CapabilityCategory.PHONE,
        description="Dispatches an encrypted push notification to user phone via ntfy or Gotify service.",
        keywords=["push notification", "notify phone", "send notification to phone", "ntfy alert"],
        examples=["Send a test notification to my phone", "Alert my phone when task finishes"],
        counterexamples=["Send text to phone", "Send WhatsApp message", "Wake greeting"],
        required_slots=["message"],
        optional_slots=["title", "priority"],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="notification_send",
        verifier="notification_ack_probe",
        cost_tier=CostTier.LOW,
    ),

    # --- WHATSAPP (4) ---
    CapabilityDefinition(
        id="whatsapp.send",
        category=CapabilityCategory.WHATSAPP,
        description="Sends a WhatsApp message to a recipient contact or phone number. Requires confirmation ticket in production.",
        keywords=["send whatsapp", "whatsapp message", "text on whatsapp", "message contact", "say hi to", "say hello to", "say to", "tell", "say", "text", "hi", "whatsapp"],
        examples=["Send a WhatsApp message to Mom saying I will be home soon", "Message Rahul on WhatsApp", "Say hi to yoga in whatsapp", "Say hi to yoga", "Tell yoga hi", "Text Rahul on whatsapp"],
        counterexamples=["Read whatsapp messages", "Summarize whatsapp", "Send text to phone"],
        required_slots=["recipient", "message"],
        optional_slots=[],
        risk_level=RiskLevel.EXTERNAL_EFFECT,
        target_tool="send_whatsapp_message",
        verifier="whatsapp_transport_ack_probe",
        cost_tier=CostTier.LOW,
    ),
    CapabilityDefinition(
        id="whatsapp.read",
        category=CapabilityCategory.WHATSAPP,
        description="Reads incoming unread or recent WhatsApp messages from the local Baileys bridge.",
        keywords=["read whatsapp", "check whatsapp messages", "unread whatsapp", "what whatsapp messages do i have"],
        examples=["Read my unread WhatsApp messages", "Check recent WhatsApp messages"],
        counterexamples=["Send whatsapp", "Summarize whatsapp", "Read file"],
        required_slots=[],
        optional_slots=["limit", "unread_only"],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="read_whatsapp_messages",
        verifier="whatsapp_read_probe",
        cost_tier=CostTier.LOW,
    ),
    CapabilityDefinition(
        id="whatsapp.summarize",
        category=CapabilityCategory.WHATSAPP,
        description="Summarizes pending WhatsApp messages requiring attention, highlighting urgent items.",
        keywords=["summarize whatsapp", "whatsapp summary", "brief me on whatsapp"],
        examples=["Summarize my WhatsApp messages", "What urgent WhatsApp messages need my attention?"],
        counterexamples=["Read whatsapp", "Morning briefing", "Meeting notes"],
        required_slots=[],
        optional_slots=[],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="summarize_whatsapp_messages",
        verifier="whatsapp_summary_probe",
        cost_tier=CostTier.LOW,
    ),
    CapabilityDefinition(
        id="whatsapp.action",
        category=CapabilityCategory.WHATSAPP,
        description="Manages WhatsApp transport bridge connectivity: pair QR, connect, or disconnect.",
        keywords=["pair whatsapp", "connect whatsapp", "reconnect whatsapp", "whatsapp qr code"],
        examples=["Re-pair WhatsApp", "Show WhatsApp pairing QR code", "Reconnect WhatsApp bridge"],
        counterexamples=["Send whatsapp message", "Read whatsapp"],
        required_slots=["action"],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="whatsapp_action",
        verifier="whatsapp_bridge_probe",
        cost_tier=CostTier.LOW,
    ),

    # --- PHONE & ANDROID (7) ---
    CapabilityDefinition(
        id="phone.status",
        category=CapabilityCategory.PHONE,
        description="Checks Android phone connection status via ADB, scrcpy availability, and battery status.",
        keywords=["phone status", "is phone connected", "android status", "phone battery", "check phone", "is mobile connected", "connected phone"],
        examples=["Is my phone connected?", "Check phone status", "Show phone battery level", "Is Android connected?"],
        counterexamples=["Open phone screen", "Send file to phone", "Microphone status"],
        required_slots=[],
        optional_slots=[],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="android_status",
        verifier="default_exit_code_verifier",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="phone.mirror_open",
        category=CapabilityCategory.PHONE,
        description="Mirrors Android phone screen directly onto PC desktop with interactive control via scrcpy.",
        keywords=["mirror phone", "show phone screen", "open scrcpy", "phone screen on pc", "control phone", "display phone", "mirror android"],
        examples=["Show my phone screen", "Mirror my phone", "Open phone control", "Open scrcpy"],
        counterexamples=["Close phone screen", "Take screenshot", "Open camera"],
        required_slots=[],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="android_open_control",
        verifier="default_exit_code_verifier",
        cost_tier=CostTier.MEDIUM,
    ),
    CapabilityDefinition(
        id="phone.mirror_close",
        category=CapabilityCategory.PHONE,
        description="Closes the active Android phone screen mirror or scrcpy window.",
        keywords=["close phone mirror", "stop mirroring phone", "close scrcpy", "exit phone control", "close phone screen"],
        examples=["Close phone screen", "Stop phone mirroring", "Exit scrcpy"],
        counterexamples=["Open phone screen", "Lock screen", "Close window"],
        required_slots=[],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="android_close_control",
        verifier="default_exit_code_verifier",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="phone.open_app",
        category=CapabilityCategory.PHONE,
        description="Launches an application directly on the connected Android mobile phone.",
        keywords=["open app on phone", "launch phone app", "open mobile app", "launch on android"],
        examples=["Open Spotify on my phone", "Launch camera on mobile", "Open WhatsApp on phone"],
        counterexamples=["Open Chrome", "Open app", "Phone status"],
        required_slots=["app_name"],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="android_open_app",
        verifier="android_open_app",
        cost_tier=CostTier.LOW,
    ),
    CapabilityDefinition(
        id="phone.send_file",
        category=CapabilityCategory.PHONE,
        description="Transfers files, photos, or documents to connected Android phone over Wi-Fi via LocalSend.",
        keywords=["send file to phone", "transfer file to mobile", "localsend file", "share file to phone", "send photo to phone"],
        examples=["Send this file to my phone", "Transfer report to mobile via LocalSend", "Send photo to phone"],
        counterexamples=["Send whatsapp message", "Copy file", "Find file"],
        required_slots=["path"],
        optional_slots=["target_alias"],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="localsend_file",
        verifier="default_exit_code_verifier",
        cost_tier=CostTier.LOW,
    ),
    CapabilityDefinition(
        id="phone.send_text",
        category=CapabilityCategory.PHONE,
        description="Sends text snippets, clipboard content, or web URLs to Android phone via LocalSend.",
        keywords=["send text to phone", "send link to phone", "share url to phone", "clipboard to phone", "localsend text"],
        examples=["Send this link to my phone", "Send text to phone via LocalSend", "Share clipboard with mobile"],
        counterexamples=["Send whatsapp message", "Save note", "Dictate text"],
        required_slots=["text"],
        optional_slots=["target_alias"],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="localsend_text",
        verifier="default_exit_code_verifier",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="phone.notification",
        category=CapabilityCategory.PHONE,
        description="Sends push alert notifications to mobile phone via ntfy or Gotify.",
        keywords=["send notification to phone", "push alert to mobile", "notify phone", "mobile alert"],
        examples=["Send notification to phone: task complete", "Push alert to mobile"],
        counterexamples=["Check phone", "Mute volume"],
        required_slots=["message"],
        optional_slots=["title", "priority"],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="notification_send",
        verifier="default_exit_code_verifier",
        cost_tier=CostTier.FREE,
    ),

    # --- GOOGLE AUTOMATIONS (4) ---
    CapabilityDefinition(
        id="google.gmail_send",
        category=CapabilityCategory.GOOGLE,
        description="Composes and sends an email draft via connected Gmail account.",
        keywords=["send email", "draft email", "gmail send", "write email to", "email contact", "send mail", "compose email"],
        examples=["Send an email to boss@company.com", "Draft email to client about project", "Compose new email to Sarah"],
        counterexamples=["Send whatsapp", "Read emails", "Check inbox"],
        required_slots=["to", "subject", "body"],
        optional_slots=[],
        risk_level=RiskLevel.EXTERNAL_EFFECT,
        target_tool="gmail_create_draft",
        verifier="default_exit_code_verifier",
        cost_tier=CostTier.LOW,
    ),
    CapabilityDefinition(
        id="google.read_emails",
        category=CapabilityCategory.GOOGLE,
        description="Reads recent or unread emails from connected Gmail inbox.",
        keywords=["read emails", "check emails", "inbox messages", "recent emails", "unread emails", "check gmail", "show my emails"],
        examples=["Check my emails", "Read recent emails from inbox", "Show my unread emails", "Do I have new emails?"],
        counterexamples=["Send email", "Read whatsapp", "Read file"],
        required_slots=[],
        optional_slots=["limit"],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="gmail_list_recent",
        verifier="default_exit_code_verifier",
        cost_tier=CostTier.LOW,
    ),
    CapabilityDefinition(
        id="google.calendar_create",
        category=CapabilityCategory.GOOGLE,
        description="Schedules a new meeting or event on Google Calendar.",
        keywords=["create calendar event", "schedule meeting", "add to calendar", "calendar appointment", "new event", "schedule appointment"],
        examples=["Schedule meeting with team tomorrow at 10am", "Add calendar event Doctor Appointment on Friday", "New calendar event Review at 3pm"],
        counterexamples=["Show calendar", "What time is it", "Set timer"],
        required_slots=["title"],
        optional_slots=["start_time", "end_time", "location"],
        risk_level=RiskLevel.EXTERNAL_EFFECT,
        target_tool="calendar_create_event",
        verifier="default_exit_code_verifier",
        cost_tier=CostTier.LOW,
    ),
    CapabilityDefinition(
        id="google.calendar_list",
        category=CapabilityCategory.GOOGLE,
        description="Lists upcoming events and appointments from Google Calendar.",
        keywords=["show calendar", "upcoming events", "what is on my schedule", "calendar agenda", "today meetings", "check my calendar"],
        examples=["What meetings do I have today?", "Show my upcoming calendar events", "Check my schedule for tomorrow"],
        counterexamples=["Schedule meeting", "Current time", "Show desktop"],
        required_slots=[],
        optional_slots=["days"],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="calendar_list_events",
        verifier="default_exit_code_verifier",
        cost_tier=CostTier.LOW,
    ),

    # --- TERMINAL (1) ---
    CapabilityDefinition(
        id="terminal.powershell",
        category=CapabilityCategory.TERMINAL,
        description="Executes a validated, policy-checked PowerShell command or script with administrative elevation if permitted.",
        keywords=["run powershell", "execute script", "powershell command", "run cmd", "terminal"],
        examples=["Run powershell Get-Process", "Execute powershell script to check disk", "cmd dir"],
        counterexamples=["Install software", "System diagnostics", "List directory"],
        required_slots=["command"],
        optional_slots=["as_admin"],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="powershell_command",
        verifier="process_exit_code_zero_probe",
        cost_tier=CostTier.LOW,
    ),

    # --- WORKFLOW & PRODUCTIVITY (16) ---
    CapabilityDefinition(
        id="workflow.save_workspace",
        category=CapabilityCategory.WORKFLOW,
        description="Saves a workspace manifest of open applications, directories, and browser tabs for later resumption.",
        keywords=["save workspace", "snapshot workspace", "save current work setup", "save session"],
        examples=["Save my workspace as 'CodingSession'", "Save workspace PythonProject"],
        counterexamples=["Launch workspace", "Save file", "Take screenshot"],
        required_slots=["name"],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="save_workspace",
        verifier="manifest_exists_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="workflow.launch_workspace",
        category=CapabilityCategory.WORKFLOW,
        description="Restores and opens apps, folders, and browser tabs saved in a workspace manifest.",
        keywords=["launch workspace", "restore workspace", "open workspace session"],
        examples=["Launch workspace 'CodingSession'", "Restore PythonProject workspace"],
        counterexamples=["Save workspace", "Open app", "Open folder"],
        required_slots=["name"],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="launch_workspace",
        verifier="workspace_restored_probe",
        cost_tier=CostTier.MEDIUM,
    ),
    CapabilityDefinition(
        id="workflow.study_focus",
        category=CapabilityCategory.WORKFLOW,
        description="Starts a distraction-free focus or study session with a countdown timer.",
        keywords=["study session", "focus mode", "start focus timer", "pomodoro"],
        examples=["Start study focus for 25 minutes", "Begin focus mode", "Focus session 45 mins"],
        counterexamples=["Set alarm", "What time is it?", "Sleep PC"],
        required_slots=[],
        optional_slots=["minutes"],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="start_study_focus",
        verifier="focus_active_probe",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="workflow.run_tests",
        category=CapabilityCategory.WORKFLOW,
        description="Executes automated unit tests (pytest) for an approved developer repository and returns metrics.",
        keywords=["run tests", "run project tests", "execute pytest", "test codebase"],
        examples=["Run project tests", "Execute unit tests for current repository", "Run pytest"],
        counterexamples=["Diagnose error", "Git status", "Run powershell"],
        required_slots=[],
        optional_slots=["project_path"],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="run_project_tests",
        verifier="test_results_probe",
        cost_tier=CostTier.MEDIUM,
    ),
    CapabilityDefinition(
        id="workflow.git_status",
        category=CapabilityCategory.WORKFLOW,
        description="Checks Git branch, staged/unstaged changes, and untracked files in an approved project directory.",
        keywords=["git status", "check git branch", "uncommitted changes", "git modified files"],
        examples=["Check git status", "What files are modified in git?", "Show git diff status"],
        counterexamples=["Run tests", "Find file", "Diagnose error"],
        required_slots=[],
        optional_slots=["repo_path"],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="git_status",
        verifier="git_probe",
        cost_tier=CostTier.LOW,
    ),
    CapabilityDefinition(
        id="workflow.diagnose_error",
        category=CapabilityCategory.WORKFLOW,
        description="Analyzes stack traces, redaction of sensitive credentials, and produces actionable fixes.",
        keywords=["diagnose error", "analyze traceback", "debug error", "why did it crash"],
        examples=["Diagnose this error traceback", "Debug error from log file"],
        counterexamples=["System diagnostics", "Run tests", "Ollama chat"],
        required_slots=["traceback"],
        optional_slots=[],
        risk_level=RiskLevel.READ_ONLY,
        target_tool="diagnose_error",
        verifier="diagnostic_fix_probe",
        cost_tier=CostTier.MEDIUM,
    ),
    CapabilityDefinition(
        id="workflow.dictate_text",
        category=CapabilityCategory.WORKFLOW,
        description="Transcribes spoken dictation, normalizes grammar, and inserts text into the active application.",
        keywords=["dictate", "start dictation", "type what I say", "voice typing"],
        examples=["Dictate text into Notepad", "Start dictation mode", "Type: Meeting confirmed for Monday"],
        counterexamples=["Capture note", "Send whatsapp", "TTS voice"],
        required_slots=["text"],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="dictate_text",
        verifier="dictate_probe",
        cost_tier=CostTier.LOW,
    ),
    CapabilityDefinition(
        id="workflow.extract_audio",
        category=CapabilityCategory.WORKFLOW,
        description="Extracts the audio track from a video file into an MP3 or WAV audio file using FFmpeg.",
        keywords=["extract audio", "convert video to mp3", "rip audio from video"],
        examples=["Extract audio from video.mp4", "Convert presentation.mp4 to audio.mp3"],
        counterexamples=["Trim media clip", "Play youtube", "Media control"],
        required_slots=["video_path"],
        optional_slots=["output_format"],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="extract_audio",
        verifier="audio_file_exists_probe",
        cost_tier=CostTier.MEDIUM,
    ),
    CapabilityDefinition(
        id="workflow.trim_clip",
        category=CapabilityCategory.WORKFLOW,
        description="Trims a section of a video or audio file given start timestamp and duration using FFmpeg.",
        keywords=["trim clip", "cut video", "slice audio", "trim video clip"],
        examples=["Trim the first 30 seconds of recording.mp4", "Cut audio from 01:00 for 45 seconds"],
        counterexamples=["Extract audio", "Take screenshot", "Play video"],
        required_slots=["file_path", "start_time", "duration"],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="trim_media_clip",
        verifier="clip_trimmed_probe",
        cost_tier=CostTier.MEDIUM,
    ),
    CapabilityDefinition(
        id="system.keyboard",
        category=CapabilityCategory.SYSTEM,
        description="Dispatches standard keyboard shortcuts: Enter, Escape, Tab, Shift+Tab, Arrow keys, Ctrl+A/C/V/X/Z/Y/F/S.",
        keywords=["press enter", "press escape", "press tab", "ctrl c", "ctrl v", "ctrl z", "keyboard shortcut"],
        examples=["Press Enter", "Press Escape", "Press Tab", "Ctrl+C", "Ctrl+V", "Press Ctrl+Z"],
        counterexamples=["Dictate text", "Click button"],
        required_slots=["key"],
        optional_slots=[],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="keyboard_shortcut",
        verifier="default_exit_code_verifier",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="system.clipboard",
        category=CapabilityCategory.SYSTEM,
        description="Reads clipboard, pastes text with clipboard preservation, or acts on selected text (explain, summarize, rewrite, copy).",
        keywords=["clipboard", "read clipboard", "paste clipboard", "explain selected text", "summarize selected text", "rewrite selected"],
        examples=["Read clipboard text", "Explain selected text", "Summarize selected text", "Paste from clipboard"],
        counterexamples=["Send text to phone", "Copy file"],
        required_slots=["action"],
        optional_slots=["text", "operation"],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="clipboard_intelligence",
        verifier="default_exit_code_verifier",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="workflow.voice_edit",
        category=CapabilityCategory.WORKFLOW,
        description="Performs voice-driven editing on active text: backspace, delete word, delete sentence, undo, redo, select, replace X with Y, capitalize, lowercase, copy, cut, paste.",
        keywords=["voice backspace", "delete last word", "delete last sentence", "voice undo", "voice redo", "replace with", "capitalize that", "make that lowercase"],
        examples=["Delete last word", "Voice backspace", "Delete last sentence", "Undo that", "Replace cat with dog", "Capitalize that"],
        counterexamples=["Delete file", "Close app"],
        required_slots=["action"],
        optional_slots=["target_text", "replacement_text"],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="voice_edit",
        verifier="default_exit_code_verifier",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="workflow.dictation_mode",
        category=CapabilityCategory.WORKFLOW,
        description="Explicitly activates or stops continuous voice typing dictation mode into any editable field.",
        keywords=["start typing", "start dictation mode", "start typing dictation", "stop typing", "stop dictation mode", "exit dictation"],
        examples=["Start typing dictation mode", "Start typing", "Stop typing mode", "Stop dictation"],
        counterexamples=["Dictate text into Notepad", "Change voice"],
        required_slots=["action"],
        optional_slots=["target_app"],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="dictation_mode_control",
        verifier="default_exit_code_verifier",
        cost_tier=CostTier.FREE,
    ),
    CapabilityDefinition(
        id="workflow.ide_control",
        category=CapabilityCategory.WORKFLOW,
        description="Automates Antigravity / VS Code IDE actions: live dictate/type prompts, open files, switch tabs, save files, open terminal/problems panels, explain visible errors, and submit prompts.",
        keywords=["open antigravity", "focus coding prompt", "type prompt into antigravity", "open terminal panel", "open problems panel", "explain visible error", "ide screenshot", "save current file in ide"],
        examples=["Open Antigravity", "Focus coding prompt", "Open problems panel", "Explain visible error", "Save current file in IDE", "Submit prompt in Antigravity"],
        counterexamples=["Open Chrome", "Diagnose error from log"],
        required_slots=["action"],
        optional_slots=["text", "path"],
        risk_level=RiskLevel.REVERSIBLE,
        target_tool="antigravity_ide_control",
        verifier="default_exit_code_verifier",
        cost_tier=CostTier.LOW,
    ),
]


def _cap(cap_id, category, description, keywords, examples, target, counter=(), required=(), optional=(),
         risk=RiskLevel.REVERSIBLE, cost=CostTier.LOW, family=""):
    return CapabilityDefinition(
        id=cap_id, category=category, description=description, keywords=list(keywords), examples=list(examples),
        counterexamples=list(counter), required_slots=list(required), optional_slots=list(optional), risk_level=risk,
        target_tool=target, cost_tier=cost, family=family,
    )


# Capabilities added with the AI integration layer (phone control, messaging replies, RAG, web, reminders).
EXTENDED_CAPABILITY_DEFINITIONS: List[CapabilityDefinition] = [
    _cap("web.open_website", CapabilityCategory.BROWSER, "Opens a website or a site's search results page in the default browser.",
         ["open website", "go to site", "visit website", "search amazon", "search flipkart", "search on youtube"],
         ["Go to wikipedia.org", "Search Amazon for wireless earbuds", "Open github.com"], "open_website",
         counter=["Search my files", "Open notepad"], required=["url"], family="BROWSER"),
    _cap("web.task", CapabilityCategory.BROWSER, "Uses the browser with AI to complete a multi-step web goal and report the result.",
         ["use the browser to", "find the price of", "look up on the website", "browse and find", "check the website"],
         ["Use the browser to find the price of a Pixel 9 on Flipkart", "Check the website for today's opening hours"], "web_task",
         counter=["Open chrome"], required=["goal"], cost=CostTier.EXPENSIVE, family="BROWSER"),
    _cap("reminder.set", CapabilityCategory.WORKFLOW, "Sets a spoken reminder for a time, e.g. in 10 minutes or at 6 pm.",
         ["remind me", "set a reminder", "reminder", "alert me at"],
         ["Remind me to drink water in 20 minutes", "Set a reminder to call mom at 6 pm"], "set_reminder",
         counter=["Remind Rahul on WhatsApp", "What time is it"], required=["text"], family="WORKFLOW"),
    _cap("reminder.list", CapabilityCategory.WORKFLOW, "Lists pending reminders.",
         ["my reminders", "list reminders", "pending reminders"], ["What are my reminders?", "Show my reminders"], "list_reminders",
         risk=RiskLevel.READ_ONLY, family="WORKFLOW"),
    _cap("rag.knowledge_ingest", CapabilityCategory.RAG, "Adds a folder or document to JARVIS's knowledge base so questions can be answered from it.",
         ["learn my documents", "index folder", "add to knowledge base", "memorize this folder", "study these files"],
         ["Learn my Documents folder", "Add D:\\Notes to your knowledge base"], "knowledge_ingest",
         counter=["Open my documents folder"], required=["path"], risk=RiskLevel.READ_ONLY, cost=CostTier.MEDIUM, family="RAG"),
    _cap("rag.knowledge_search", CapabilityCategory.RAG, "Answers a question from the knowledge base (indexed documents and notes) with citations.",
         ["what do my documents say", "search my knowledge base", "according to my notes", "ask my documents"],
         ["What do my documents say about the refund policy?", "Search my knowledge base for the project deadline"], "knowledge_search",
         counter=["Find a file named report"], required=["question"], risk=RiskLevel.READ_ONLY, cost=CostTier.MEDIUM, family="RAG"),
    _cap("whatsapp.reply", CapabilityCategory.WHATSAPP, "Drafts a reply to the latest WhatsApp message from someone and asks before sending.",
         ["reply to", "respond to message", "answer the message", "write back"],
         ["Reply to Rahul saying I'll be there at 6", "Reply to the last WhatsApp message"], "reply_whatsapp_message",
         counter=["Send a new message to mom"], optional=["recipient", "instruction"], risk=RiskLevel.READ_ONLY, family="WHATSAPP"),
    _cap("app.uninstall_software", CapabilityCategory.APP, "Uninstalls an installed application after confirmation (winget).",
         ["uninstall", "remove app", "remove program", "delete application"],
         ["Uninstall VLC", "Remove the Zoom app from my laptop"], "uninstall_software",
         counter=["Delete the file report.pdf", "Install VLC"], required=["name"], risk=RiskLevel.DESTRUCTIVE, cost=CostTier.EXPENSIVE, family="APP"),
    _cap("app.update_software", CapabilityCategory.APP, "Updates one application or all applications that have updates (winget upgrade).",
         ["update apps", "upgrade software", "update all my apps", "check for app updates"],
         ["Update all my apps", "Update the Chrome app"], "update_software",
         counter=["Update Windows", "Install VLC"], optional=["name"], cost=CostTier.EXPENSIVE, family="APP"),
    _cap("whatsapp.reply_all", CapabilityCategory.WHATSAPP, "Replies to everyone who messaged recently (personal chats only, groups skipped) with one message, personalised per person, after confirmation.",
         ["reply to everyone who messaged me", "tell everyone who texted me", "reply to all my messages", "message all the people who pinged me"],
         ["Tell everyone who messaged me that I'm in a meeting", "Reply to all the people texting me that I'll call back in an hour"], "reply_whatsapp_all",
         counter=["Reply to Rahul", "Send a message to mom"], optional=["message"], risk=RiskLevel.READ_ONLY, family="WHATSAPP"),
    _cap("phone.notifications", CapabilityCategory.PHONE, "Reads the notifications showing on the phone.",
         ["phone notifications", "read my notifications", "what notifications do i have", "check my phone"],
         ["Read my phone notifications", "Any notifications on my phone?"], "android_notifications",
         counter=["Send a notification to my phone", "Read my WhatsApp messages"], risk=RiskLevel.READ_ONLY, family="PHONE"),
    _cap("phone.tap_text", CapabilityCategory.PHONE, "Taps a button or item by its label on the phone screen.",
         ["tap on phone", "press button on phone", "click on my phone"], ["Tap Settings on my phone", "Press Allow on my phone"],
         "android_tap_text", counter=["Click the button on my PC"], required=["text"], family="PHONE"),
    _cap("phone.toggle", CapabilityCategory.PHONE, "Turns phone Wi-Fi, Bluetooth, mobile data, airplane mode or do-not-disturb on or off.",
         ["turn on wifi on phone", "phone bluetooth off", "airplane mode on my phone", "do not disturb on phone"],
         ["Turn off Bluetooth on my phone", "Turn on Wi-Fi on my phone"], "android_toggle",
         counter=["Turn off wifi on my laptop"], required=["setting"], family="PHONE"),
    _cap("vision.describe_screen", CapabilityCategory.SYSTEM, "Looks at the PC or phone screen with the local vision model and answers questions about it.",
         ["what's on my screen", "look at my screen", "read my screen", "what does this error say", "describe my screen"],
         ["What is this error on my screen?", "Look at my phone screen and tell me what it says"], "describe_screen",
         counter=["Take a screenshot"], optional=["question", "device"], risk=RiskLevel.READ_ONLY, cost=CostTier.MEDIUM, family="VISION"),
    _cap("phone.key", CapabilityCategory.PHONE, "Presses phone keys: volume, lock or wake the screen, play or pause media, home, back.",
         ["phone volume", "lock my phone", "wake my phone", "pause music on phone", "next song on phone"],
         ["Turn up the volume on my phone", "Lock my phone", "Pause the music on my phone"], "android_key",
         counter=["Turn up the volume", "Lock the PC"], required=["key"], family="PHONE"),
    _cap("phone.input", CapabilityCategory.PHONE, "Types text, taps or swipes on the connected phone.",
         ["type on my phone", "swipe on phone", "tap on phone"], ["Type hello on my phone", "Swipe up on my phone"], "android_input",
         required=["action"], family="PHONE"),
    _cap("phone.open_url", CapabilityCategory.PHONE, "Opens a web page on the phone's browser.", ["open website on phone", "open link on my phone"],
         ["Open youtube.com on my phone"], "android_open_url", required=["url"], family="PHONE"),
    _cap("phone.dial", CapabilityCategory.PHONE, "Opens the phone dialer with a number or contact ready to call.",
         ["call on my phone", "dial number", "phone call"], ["Call 9876543210 on my phone", "Dial mom on my phone"], "android_dial",
         counter=["Call Arun on WhatsApp"], required=["number"], family="PHONE"),
    _cap("phone.screenshot", CapabilityCategory.PHONE, "Takes a screenshot of the phone screen and saves it on the PC.",
         ["phone screenshot", "screenshot of my phone", "capture phone screen"], ["Take a screenshot of my phone"], "android_screenshot",
         counter=["Take a screenshot"], family="PHONE"),
]

class CapabilityRegistry:
    """In-memory indexing and catalog management for all system capabilities."""

    def __init__(self, tool_registry: Optional[ToolRegistry] = None) -> None:
        self.tool_registry = tool_registry
        self._capabilities: Dict[str, CapabilityDefinition] = {}
        self._tool_to_cap: Dict[str, CapabilityDefinition] = {}
        self._category_index: Dict[CapabilityCategory, List[CapabilityDefinition]] = {c: [] for c in CapabilityCategory}

        # Index master definitions
        for cap in CAPABILITY_DEFINITIONS + EXTENDED_CAPABILITY_DEFINITIONS:
            self.register(cap)

    def register(self, cap: CapabilityDefinition) -> None:
        self._capabilities[cap.id] = cap
        self._tool_to_cap[cap.target_tool] = cap
        if cap not in self._category_index[cap.category]:
            self._category_index[cap.category].append(cap)

    def get(self, cap_id: str) -> Optional[CapabilityDefinition]:
        return self._capabilities.get(cap_id)

    def get_by_tool(self, tool_name: str) -> Optional[CapabilityDefinition]:
        return self._tool_to_cap.get(tool_name)

    def list_all(self) -> List[CapabilityDefinition]:
        return sorted(self._capabilities.values(), key=lambda c: (c.category, c.id))

    def list_by_category(self, category: CapabilityCategory) -> List[CapabilityDefinition]:
        return self._category_index.get(category, [])

    def export_markdown_catalog(self, output_path: Path | str) -> None:
        """
        Generates docs/CAPABILITY_CATALOG.md strictly containing:
        ID, DESCRIPTION, INPUT, OUTPUT, RISK, DEPENDENCIES, VERIFIER, AVAILABILITY, EXAMPLES, COUNTEREXAMPLES.
        """
        out = Path(output_path)
        out.parent.mkdir(parents=True, exist_ok=True)

        lines: List[str] = [
            "# JARVIS EDGE: Master Capability Catalog",
            "",
            "This catalog provides the complete, authoritative machine- and human-readable map of every executable capability supported by the JARVIS EDGE brain. It is automatically generated from `CapabilityRegistry` and synchronized with `ToolRegistry`.",
            "",
            f"**Total Registered Capabilities**: {len(self._capabilities)}",
            "",
            "---",
            "",
        ]

        # Group by category
        for cat in CapabilityCategory:
            caps = self.list_by_category(cat)
            if not caps:
                continue

            lines.append(f"## {cat.value} Capabilities ({len(caps)})\n")

            for cap in caps:
                # Extract input and output schema info from tool_registry if available
                input_schema = "{}"
                output_schema = "{}"
                if self.tool_registry and self.tool_registry.contains(cap.target_tool):
                    t = self.tool_registry.get(cap.target_tool)
                    input_schema = json.dumps(t.definition.input_model.model_json_schema().get("properties", {}), indent=2)
                    output_schema = json.dumps(t.definition.output_model.model_json_schema().get("properties", {}), indent=2)
                else:
                    input_schema = json.dumps({s: "string" for s in cap.required_slots + cap.optional_slots}, indent=2)
                    output_schema = '{\n  "status": "string",\n  "data": "object"\n}'

                verifier_str = cap.verifier or get_verifier_for_tool(cap.target_tool)
                deps_str = ", ".join(cap.dependencies) if cap.dependencies else "Standard Windows Environment"
                avail_str = cap.availability_check or "Always Available (Local Host)"

                lines.extend([
                    f"### `{cap.id}`",
                    "",
                    f"- **DESCRIPTION**: {cap.description}",
                    f"- **TARGET TOOL**: `{cap.target_tool}`",
                    f"- **RISK**: `{cap.risk_level.name}`",
                    f"- **COST TIER**: `{cap.cost_tier.value}`",
                    f"- **DEPENDENCIES**: {deps_str}",
                    f"- **VERIFIER**: `{verifier_str}`",
                    f"- **AVAILABILITY**: {avail_str}",
                    "",
                    "#### INPUT SCHEMA",
                    "```json",
                    input_schema,
                    "```",
                    "",
                    "#### OUTPUT SCHEMA",
                    "```json",
                    output_schema,
                    "```",
                    "",
                    "#### EXAMPLES",
                ])

                for ex in cap.examples:
                    lines.append(f"- \"{ex}\"")

                lines.append("")
                lines.append("#### COUNTEREXAMPLES")
                for cex in cap.counterexamples:
                    lines.append(f"- \"{cex}\"")

                lines.append("")
                lines.append("---")
                lines.append("")

        out.write_text("\n".join(lines), encoding="utf-8")
        print(f"Successfully generated Capability Catalog at {out} ({len(self._capabilities)} capabilities)")


_GLOBAL_CAPABILITY_REGISTRY: Optional[CapabilityRegistry] = None

def get_default_capability_registry(tool_registry: Optional[ToolRegistry] = None) -> CapabilityRegistry:
    global _GLOBAL_CAPABILITY_REGISTRY
    if _GLOBAL_CAPABILITY_REGISTRY is None:
        _GLOBAL_CAPABILITY_REGISTRY = CapabilityRegistry(tool_registry=tool_registry)
    elif tool_registry and _GLOBAL_CAPABILITY_REGISTRY.tool_registry is None:
        _GLOBAL_CAPABILITY_REGISTRY.tool_registry = tool_registry
    return _GLOBAL_CAPABILITY_REGISTRY
