"""BLIND-3: third held-out set with more easy commands, written after the blind-2 fixes and scored once before fixing.

New phrasings and new names/apps/files for every phase. Same expectation codes as ``cases.py``.
"""
from __future__ import annotations

from tests.phase_suite.blind2 import build_split
from tests.phase_suite.cases import TIERS, T

E, M, H, V = TIERS

POOLS = {
    "app": ["vivaldi", "signal", "zotero", "obsidian", "inkscape", "krita", "bitwarden", "libreoffice", "dbeaver", "insomnia"],
    "p": ["deepa", "vijay", "swathi", "mani", "keerthi", "prakash", "paati", "thatha"],
    "n": ["8", "18", "33", "42", "57", "64", "78", "88"],
    "msg": ["class is cancelled", "call me after 6", "i'm stuck in traffic", "the parcel arrived", "lunch is ready",
            "check your email"],
    "file": ["gas bill", "pan card", "project proposal", "lab record", "visa letter"],
    "fname": ["report_final.pdf", "expenses.csv", "banner.jpg", "essay.docx", "intro.mp3"],
    "folder": ["downloads", "documents", "pictures", "videos"],
    "site": ["stackexchange.com", "nytimes.com", "khanacademy.org", "swiggy.com", "hotstar.com"],
    "q": ["ergonomic chair", "usb hub", "sunscreen", "wireless charger", "running socks"],
    "song": ["harris jayaraj songs", "lofi hip hop", "taylor swift", "ed sheeran", "90s tamil hits"],
    "city": ["salem", "vellore", "goa", "ooty"],
    "topic": ["maternity leave", "fee structure", "placement rules", "refund window"],
}

PHASES3: dict[str, list[T]] = {
    "p01_core_os": [
        T(E, "start {app}", "open_app", {"name": "{app}"}),
        T(E, "close {app} now", "close_app", {"name": "{app}"}),
        T(E, "mute the volume", "volume_mute|mute"),
        T(E, "volume up please", "volume_up"),
        T(E, "volume down a bit", "volume_down"),
        T(E, "set the volume to {n}", "volume_set", {"percent": "{n}"}),
        T(E, "screenshot please", "take_screenshot"),
        T(E, "lock the computer", "system_power_control|lock_pc"),
        T(M, "can you shut {app} down", "close_app"),
        T(M, "raise the volume a little", "volume_up"),
        T(M, "lower the brightness to {n}", "brightness_set", {"percent": "{n}"}),
        T(M, "put my laptop to sleep", "system_power_control"),
        T(M, "restart the computer now", "system_power_control"),
        T(M, "how much charge do i have left", "battery_status"),
        T(M, "go to my documents folder", "open_known_folder"),
        T(H, "the screen is too bright", "brightness_set"),
        T(H, "i can barely hear anything", "volume_up"),
        T(V, "{app} needs to be closed", "close_app"),
    ],
    "p02_router": [
        T(E, "what is {app} good for", "CHAT"),
        T(E, "how is your day going", "CHAT"),
        T(M, "how do i close {app}", "CHAT"),
        T(M, "what is {city} famous for", "CHAT|search_web"),
        T(M, "is it safe to delete temp files", "CHAT"),
        T(M, "explain how wifi works", "CHAT"),
        T(H, "i want to open {app}", "open_app", {"name": "{app}"}),
        T(H, "what happens if i close {app}", "CHAT"),
        T(V, "should i use {app} or {app2} for this", "CHAT"),
        T(M, "why is my pc so slow", "CHAT|system_diagnostics|top_memory_processes"),
    ],
    "p03_files": [
        T(E, "find {file}", "find_file"),
        T(E, "list my {folder}", "list_directory|open_known_folder"),
        T(M, "search for the {file} file", "find_file"),
        T(M, "copy {fname} to desktop", "copy_file"),
        T(M, "shift {fname} into my documents", "move_file"),
        T(M, "delete the file {fname}", "delete_file+clarify"),
        T(M, "rename {fname} as draft two", "rename_file"),
        T(M, "create a folder named {topic}", "create_folder"),
        T(M, "what is the size of {fname}", "read_file_metadata"),
        T(H, "where's my {file}", "find_file"),
        T(H, "look for my {file} somewhere on this laptop", "find_file"),
        T(H, "sort out my downloads folder", "organize_downloads"),
        T(H, "find duplicate files in my {folder}", "find_duplicates"),
        T(V, "i saved the {file} somewhere last week, find it", "find_file"),
    ],
    "p04_multistep": [
        T(E, "launch {app} and {app2} together", "MULTI"),
        T(M, "mute and lock the screen", "MULTI"),
        T(M, "open {app} then take a screenshot", "MULTI"),
        T(H, "quit {app}, start {app2} and make the volume {n}", "MULTI"),
        T(H, "play {song} on youtube and set the volume to {n}", "MULTI"),
        T(V, "first take a screenshot, then open {app}, then mute", "MULTI"),
        T(M, "open {site} and then open {app}", "MULTI"),
    ],
    "p05_safety": [
        T(E, "do not launch {app}", "REJECT"),
        T(M, "please don't mute", "REJECT"),
        T(M, "do not delete {fname}", "REJECT"),
        T(M, "erase every file on my computer", "SAFE|delete_file+clarify"),
        T(M, "wipe the c drive", "SAFE"),
    ],
    "p06_voice_input": [
        T(E, "jarvis open {app}", "open_app", {"name": "{app}"}),
        T(E, "hey jarvis what's the time", "get_time"),
        T(M, "jarvis, mute", "volume_mute|mute"),
        T(M, "um, open {app}", "open_app"),
        T(H, "uh jarvis can you uh open {app}", "open_app"),
        T(H, "Jarvis. Volume {n}.", "volume_set"),
        T(V, "open open {app}", "open_app"),
        T(V, "jarvis jarvis open {app}", "open_app"),
        T(M, "is my mic on", "microphone_status"),
        T(M, "turn on voice typing", "dictation_mode_control"),
    ],
    "p07_voice_output": [
        T(E, "quiet", "CONTROL:stop_speaking"),
        T(M, "switch your voice to a woman's voice", "set_voice"),
        T(M, "i prefer a male voice", "set_voice"),
        T(M, "repeat that please", "recent_actions"),
        T(M, "talk to me in thanglish", "set_reply_language"),
        T(M, "reply in english from now on", "set_reply_language"),
        T(H, "sorry, what did you say", "recent_actions"),
    ],
    "p08_history": [
        T(E, "what did you do", "recent_actions"),
        T(M, "show my recent commands", "command_history"),
        T(M, "what did i tell you to do earlier today", "command_history"),
        T(H, "did you send my message to {p}", "recent_actions"),
        T(H, "who did you send it to", "recent_actions"),
        T(V, "hold on, was that message actually sent", "recent_actions"),
        T(M, "what was my last command", "command_history|recent_actions"),
    ],
    "p09_google": [
        T(E, "check my inbox", "gmail_list_recent"),
        T(E, "read my emails", "gmail_list_recent"),
        T(E, "what's on my calendar", "calendar_list_events"),
        T(M, "any emails from {p}", "gmail_list_recent"),
        T(M, "do i have meetings tomorrow", "calendar_list_events"),
        T(M, "what's my schedule today", "calendar_list_events"),
        T(H, "am i busy on saturday evening", "calendar_list_events"),
        T(H, "email {p} about the {topic}", "gmail_create_draft+clarify"),
        T(H, "book a meeting with {p} on friday at 11", "calendar_create_event+clarify"),
        T(V, "set up a call with {p} next monday at 3 pm", "calendar_create_event+clarify"),
    ],
    "p10_browser": [
        T(E, "open {site}", "open_website"),
        T(E, "search for {q} on google", "open_website|search_web"),
        T(E, "new tab", "browser_quick_action"),
        T(M, "play {song} on youtube please", "play_youtube"),
        T(M, "search youtube for {song}", "play_youtube|open_website"),
        T(M, "go forward", "browser_quick_action"),
        T(M, "reload the page", "browser_quick_action"),
        T(M, "zoom in", "browser_quick_action"),
        T(H, "find {q} on amazon", "open_website|web_task"),
        T(M, "what's the latest news", "search_news|search_web"),
        T(M, "news about {city}", "search_news|search_web"),
    ],
    "p11_vision": [
        T(E, "describe what's on my screen", "describe_screen"),
        T(M, "what's written on my screen", "describe_screen"),
        T(M, "click on {app}", "screen_click"),
        T(M, "double click the {app} icon", "screen_click"),
        T(H, "what is this popup saying", "describe_screen"),
        T(H, "right click the start button", "screen_click"),
        T(V, "can you read this error for me", "describe_screen|diagnose_error"),
    ],
    "p12_intelligence": [
        T(E, "remind me to drink water at 5", "set_reminder"),
        T(E, "add milk to my to do list", "todo"),
        T(E, "show my to do list", "todo"),
        T(M, "remember that {p}'s birthday is on june 5", "remember_fact"),
        T(M, "what do you know about {p}", "recall_facts|contact_info"),
        T(M, "set a 5 minute timer", "set_reminder"),
        T(M, "start a stopwatch", "stopwatch"),
        T(M, "create a password", "generate_password"),
        T(M, "what are my reminders", "list_reminders"),
        T(M, "tick off {q} from my list", "todo"),
        T(H, "remind me in 20 minutes to check the oven", "set_reminder"),
        T(H, "search my notes about {topic}", "search_notes|knowledge_search"),
        T(V, "whenever i say study time, open {app} and mute", "create_shortcut"),
    ],
    "x_whatsapp": [
        T(E, "text {p} quickly that {msg}", "send_whatsapp_message", {"recipient": "{p}"}),
        T(E, "read my whatsapp", "read_whatsapp_messages"),
        T(M, "message {p} saying {msg}", "send_whatsapp_message", {"recipient": "{p}"}),
        T(M, "tell {p} that {msg}", "send_whatsapp_message", {"recipient": "{p}"}),
        T(M, "any unread whatsapp messages", "read_whatsapp_messages|summarize_whatsapp_messages"),  # as blind-2
        T(M, "who texted me today", "summarize_whatsapp_messages"),
        T(H, "what has {p} sent me", "read_whatsapp_messages", {"sender": "{p}"}),
        T(H, "reply to {p}'s message saying {msg}", "reply_whatsapp_message|send_whatsapp_message"),
        T(H, "ask {p} whether the class is on", "send_whatsapp_message"),
        T(V, "ping {p} on whatsapp and say {msg}", "send_whatsapp_message"),
        T(M, "summarize my whatsapp chats", "summarize_whatsapp_messages"),
        T(H, "stop auto reply", "whatsapp_auto_reply"),
    ],
    "x_phone": [
        T(E, "phone battery", "android_status"),
        T(E, "screenshot my phone screen", "android_screenshot"),
        T(M, "disable bluetooth on my mobile", "android_toggle"),
        T(M, "open whatsapp on my phone", "android_open_app"),
        T(M, "what notifications are on my phone", "android_notifications"),
        T(M, "copy the latest photos from my phone", "android_pull_file"),
        T(M, "go back on my phone", "android_back|android_key"),
        T(H, "put my phone on silent", "android_toggle|android_quick_action|android_key"),
        T(H, "ring {p} from my mobile", "android_dial|android_dial+clarify|CLARIFY"),
        T(M, "show my phone screen on the pc", "android_open_control|android_quick_action"),
    ],
    "x_automation": [
        T(E, "install {app} for me", "install_software"),
        T(E, "uninstall {app} from this pc", "uninstall_software+clarify"),
        T(M, "update {app}", "update_software"),
        T(M, "check if {app} is installed", "check_app_installed"),
        T(M, "where is {app} located", "get_app_location"),
        T(M, "list installed apps", "list_installed_applications"),
        T(M, "tidy up my downloads", "organize_downloads"),
        T(M, "save this workspace as work", "save_workspace"),
        T(M, "open my study workspace", "launch_workspace"),
        T(M, "focus mode for 45 minutes", "start_study_focus"),
        T(H, "empty my recycle bin", "empty_recycle_bin+clarify"),
    ],
    "x_thanglish": [
        T(E, "{app} launch pannu", "open_app"),
        T(E, "{app} close pannu da", "close_app"),
        T(M, "volume {n} vachidu", "volume_set"),
        T(M, "sound konjam jaasthi pannu", "volume_up"),
        T(E, "battery evlo", "battery_status"),
        T(M, "screenshot eduda", "take_screenshot"),
        T(H, "{p} kitta {msg} nu sollu", "send_whatsapp_message"),
        T(M, "{song} youtube la play pannu", "play_youtube"),
        T(E, "mute pannu da", "volume_mute|mute"),
        T(M, "time ennachu", "get_time"),
    ],
    "x_chat": [
        T(E, "hi", "CHAT|wake_greeting"),
        T(E, "thank you so much", "CHAT"),
        T(E, "good night", "CHAT"),
        T(M, "tell me a riddle", "CHAT"),
        T(M, "i'm bored, entertain me", "CHAT"),
        T(M, "what exactly is deep learning", "CHAT"),
        T(M, "who are you", "CHAT"),
        T(H, "can you suggest a movie for tonight", "CHAT"),
        T(H, "write a small story about a robot", "CHAT"),
        T(V, "honestly i'm stressed about exams", "CHAT"),
        T(M, "what's the meaning of life", "CHAT"),
    ],
}


def build3() -> list[dict]:
    return build_split(PHASES3, POOLS, "blind3")
