"""Build docs/BLIND10_REPORT.md from a runner JSON: python -m tests.blind10.report <run.json> <out.md>"""
from __future__ import annotations

import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from tests.blind10.audit import ACCEPT  # noqa: E402
from tests.blind10.runner import metrics, per_tool  # noqa: E402

NAMES = {"p01_core_os": "Core OS (apps, volume, power)", "p02_router": "Router (casual, typos, mixed)", "p03_files": "Files",
         "p04_multistep": "Multi-step", "p05_safety": "Safety", "p06_voice_input": "Voice input / dictation / keys",
         "p07_voice_output": "Voice output / speech", "p08_history": "History and memory", "p09_google": "Google (Gmail, Calendar)",
         "p10_browser": "Browser control", "p11_vision": "Vision / screen", "p12_intelligence": "Intelligence / knowledge",
         "x_automation": "Automation (watches, schedules)", "x_chat": "Chat", "x_operator": "Operator (text, UI, windows)",
         "x_pc_control": "PC control (settings, apps)", "x_phone": "Phone", "x_phone_control": "Phone calls / keys",
         "x_thanglish": "Thanglish", "x_whatsapp": "WhatsApp", "x_workflows": "Workflows / dev projects",
         "z_browser_automation": "Browser automation (web agent, forms)"}


def bucket(r: dict) -> str:
    if r["ok"]:
        return "correct"
    lane, _, intent = r["got"].partition(" ")
    if r["acted"]:
        tools = [o.replace("+clarify", "") for o in r["expect"].split("|")]
        if intent in tools:
            return "right tool, wrong details"
        return "acted on must-not-act" if r["cls"] == "none" else "wrong action"
    return {"LANE_2": "left to the AI model", "CLARIFY": "asked instead", "REJECT": "refused"}.get(lane, "other")


def pct(x: float) -> str:
    return f"{100 * x:.1f}%"


def main(src: str, out: str) -> None:
    rows = json.load(open(src))["rows"]
    for r in rows:
        r["args"] = r["args"].replace("|", ";")
    audited = [{**r, "ok": True, "critical": False} if (not r["ok"] and r["text"] in ACCEPT) else r for r in rows]
    by, by_a = defaultdict(list), defaultdict(list)
    for r, a in zip(rows, audited):
        by[r["phase"]].append(r)
        by_a[a["phase"]].append(a)
    L = []
    s, a = metrics(rows), metrics(audited)
    L += ["# Blind-10: 50 unseen commands per phase, strict right-action scoring", "",
          "Report generated by `python -m tests.blind10.report`. The set is in `tests/blind10` (frozen with `FROZEN.sha256` before "
          "its first run).", "",
          "## How it was scored", "",
          "- **Unseen.** 1,100 commands, 50 in each of 22 phases (the 21 Phase-500 areas plus browser automation).",
          "  - They were written new for this test.",
          "  - Every one was checked against every earlier test file, and none appears there word for word.",
          "  - No fix was made between writing them and running them.",
          "- **Right action, not just any action.** A command is correct only when the right tool is chosen *and* its arguments "
          "contain the right details (the app, the person, the number, the query, the file).",
          "- **Must-not-act commands.** Each phase has commands that must *not* act: dangerous, vague or chat. Acting on them "
          "counts against precision.",
          "- **Metrics:**",
          "  - **Accuracy:** correct outcomes / all commands.",
          "  - **Precision:** right actions / all actions JARVIS took. Doing the wrong thing lowers it.",
          "  - **Recall:** right actions / commands that needed an action. Asking or handing over instead lowers it.",
          "  - **F1:** the harmonic mean of precision and recall.",
          "  - **Critical:** a wrong action that is consequential (delete, send, close, install, power ...).",
          "- **Router only, no AI model.** Commands the router hands to the local model (Ollama) count as misses here, because "
          "this run has no model. With Ollama running, some of them would be answered or planned correctly. That part is not "
          "measured.",
          "- **Same author.** I wrote this set and the router's rules, which may still flatter the numbers.", "",
          "## Overall", "",
          "| | Accuracy | Precision | Recall | F1 | Wrong actions | Missed | Acted on must-not-act | Critical |",
          "|---|---:|---:|---:|---:|---:|---:|---:|---:|"]
    for name, m in (("Strict (as frozen)", s), ("After the expectation audit", a)):
        L.append(f"| {name} | **{pct(m['accuracy'])}** | {pct(m['precision'])} | {pct(m['recall'])} | {pct(m['f1'])} | "
                 f"{m['wrong_actions']} | {m['missed']} | {m['false_actions']} / {m['none_cases']} | {m['critical']} |")
    L += ["", f"The audit (`tests/blind10/audit.py`) accepts {len(ACCEPT)} cases. In each, JARVIS chose an equally correct "
          "action that my expectation did not list, or my rewording left a typo in the expected details. Each case and its "
          "reason is in that file.", "",
          "### What happened on the failures (audited)", "", "| Outcome | Commands |", "|---|---:|"]
    for k, v in Counter(bucket(r) for r in audited).most_common():
        L.append(f"| {k} | {v} |")
    L += ["", "## Per phase (audited)", "",
          "| Phase | Accuracy | Precision | Recall | F1 | Wrong | Missed | Acted on must-not-act | Critical | Strict accuracy |",
          "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|"]
    for ph in by:
        m, ms = metrics(by_a[ph]), metrics(by[ph])
        L.append(f"| {NAMES.get(ph, ph)} | **{pct(m['accuracy'])}** | {pct(m['precision'])} | {pct(m['recall'])} | {pct(m['f1'])} | "
                 f"{m['wrong_actions']} | {m['missed']} | {m['false_actions']} / {m['none_cases']} | {m['critical']} | {pct(ms['accuracy'])} |")
    L += ["", "## Every critical wrong action", "", "| Phase | Said | JARVIS chose | Should have |", "|---|---|---|---|"]
    for r in audited:
        if r["critical"]:
            L.append(f"| {NAMES.get(r['phase'], r['phase'])} | {r['text']} | `{r['got'].split()[1]}` ({r['args'][:50]}) | {r['expect']} |")
    L += ["", "## Per phase: what failed", ""]
    for ph in by:
        fails = [r for r in by_a[ph] if not r["ok"]]
        L += [f"### {NAMES.get(ph, ph)}: {50 - len(fails)} / 50", ""]
        if not fails:
            L += ["Every command right.", ""]
            continue
        L += ["| Said | Outcome | JARVIS chose | Expected |", "|---|---|---|---|"]
        for r in fails:
            L.append(f"| {r['text']} | {bucket(r)} | {r['got']} {('(' + r['args'][:40] + ')') if r['args'] else ''} | "
                     f"{r['expect'][:60]} {' '.join(r['need'])} |")
        L.append("")
    L += ["## Per tool (audited): precision and recall", "",
          "Recall uses the first listed tool of each action case. Precision counts every time JARVIS chose that tool.", "",
          "| Tool | Needed | Taken | Right | Precision | Recall |", "|---|---:|---:|---:|---:|---:|"]
    for t, v in sorted(per_tool(audited).items(), key=lambda kv: -(kv[1]["gold"] + kv[1]["taken"])):
        if v["gold"] + v["taken"] < 3:
            continue
        p = "-" if v["precision"] is None else pct(v["precision"])
        rc = "-" if v["recall"] is None else pct(v["recall"])
        L.append(f"| {t} | {v['gold']} | {v['taken']} | {v['correct']} | {p} | {rc} |")
    def cell_safe(line: str) -> str:   # "a|b" inside a table cell would split it
        if not line.startswith("| ") or line.startswith("|---"):
            return line
        cells = line[2:-2].split(" | ")
        return "| " + " | ".join(c.replace("|", " / ") for c in cells) + " |"
    Path(out).write_text("\n".join(cell_safe(x) for x in L) + "\n")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
